-- =========================================================
-- LINGUA QUEST - RANKED INITIAL DATA
-- PostgreSQL
-- =========================================================


-- =========================================================
-- 1. MATCH ANSWERS
-- =========================================================

CREATE TABLE IF NOT EXISTS matchanswers
(
    matchanswerid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    matchid BIGINT NOT NULL,

    matchquestionid BIGINT NOT NULL,

    userid INTEGER NOT NULL,

    answertext VARCHAR(500),

    iscorrect BOOLEAN NOT NULL DEFAULT FALSE,

    score INTEGER NOT NULL DEFAULT 0,

    answertimemilliseconds INTEGER,

    answeredat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_matchanswers_matches
        FOREIGN KEY (matchid)
        REFERENCES matches(matchid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchanswers_questions
        FOREIGN KEY (matchquestionid)
        REFERENCES matchquestions(matchquestionid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchanswers_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT uq_matchanswer
        UNIQUE(matchquestionid, userid)
);


-- =========================================================
-- 2. RANK TIERS
-- =========================================================

INSERT INTO ranktiers
(
    rankname,
    rankorder,
    minrating,
    maxrating,
    description
)
SELECT *
FROM (
    VALUES
    (
        'Bronze',
        1,
        0,
        1199,
        'Bắt đầu hành trình ranked.'
    ),
    (
        'Silver',
        2,
        1200,
        1499,
        'Bạn đã có nền tảng tốt.'
    ),
    (
        'Gold',
        3,
        1500,
        1799,
        'Khả năng ngôn ngữ nổi bật.'
    ),
    (
        'Platinum',
        4,
        1800,
        2149,
        'Nhóm người học xuất sắc.'
    ),
    (
        'Diamond',
        5,
        2150,
        NULL,
        'Đỉnh cao của mùa giải.'
    )
) AS v(
    rankname,
    rankorder,
    minrating,
    maxrating,
    description
)
WHERE NOT EXISTS (
    SELECT 1
    FROM ranktiers
);


-- =========================================================
-- 3. RANK SEASON
-- =========================================================

INSERT INTO rankseasons
(
    seasonname,
    startdate,
    enddate,
    isactive
)
SELECT
    'Season 1 - First Words',
    NOW(),
    NOW() + INTERVAL '3 months',
    TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM rankseasons
    WHERE isactive = TRUE
);


-- =========================================================
-- 4. KIỂM TRA DỮ LIỆU
-- =========================================================

SELECT
    ranktierid,
    rankname,
    rankorder,
    minrating,
    maxrating,
    description
FROM ranktiers
ORDER BY rankorder;


SELECT
    seasonid,
    seasonname,
    startdate,
    enddate,
    isactive
FROM rankseasons
ORDER BY seasonid;