-- =========================================================
-- LINGUA QUEST - POSTGRESQL
-- Learning Website Database
-- =========================================================

-- =========================================================
-- 1. XÓA BẢNG CŨ
-- =========================================================

DROP TABLE IF EXISTS userrewards CASCADE;
DROP TABLE IF EXISTS rewards CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS leaderboard CASCADE;
DROP TABLE IF EXISTS dailystreaks CASCADE;
DROP TABLE IF EXISTS userachievements CASCADE;
DROP TABLE IF EXISTS achievements CASCADE;
DROP TABLE IF EXISTS gamesessions CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS quizanswers CASCADE;
DROP TABLE IF EXISTS quizattempts CASCADE;
DROP TABLE IF EXISTS quizquestions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS uservocabulary CASCADE;
DROP TABLE IF EXISTS vocabularyexamples CASCADE;
DROP TABLE IF EXISTS vocabulary CASCADE;
DROP TABLE IF EXISTS userlessonprogress CASCADE;
DROP TABLE IF EXISTS lessons CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS userlanguages CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- =========================================================
-- 2. USERS
-- =========================================================

CREATE TABLE users (
    userid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwordhash VARCHAR(255) NOT NULL,

    fullname VARCHAR(100),
    avatarurl VARCHAR(500),
    dateofbirth DATE,
    gender VARCHAR(20),
    country VARCHAR(100),
    bio VARCHAR(500),

    xp INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    coins INTEGER NOT NULL DEFAULT 0,

    hearts INTEGER NOT NULL DEFAULT 5,
    maxhearts INTEGER NOT NULL DEFAULT 5,

    ispremium BOOLEAN NOT NULL DEFAULT FALSE,
    isactive BOOLEAN NOT NULL DEFAULT TRUE,

    role VARCHAR(20) NOT NULL DEFAULT 'User',

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    lastloginat TIMESTAMPTZ
);


-- =========================================================
-- 3. SUBSCRIPTIONS
-- =========================================================

CREATE TABLE subscriptions (
    subscriptionid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    planname VARCHAR(100) NOT NULL,
    price NUMERIC(12,2) NOT NULL DEFAULT 0,

    startdate TIMESTAMPTZ NOT NULL,
    enddate TIMESTAMPTZ,

    status VARCHAR(30) NOT NULL DEFAULT 'Active',
    paymentmethod VARCHAR(50),
    transactioncode VARCHAR(100),

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_subscriptions_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE
);


-- =========================================================
-- 4. LANGUAGES
-- =========================================================

CREATE TABLE languages (
    languageid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    languagecode VARCHAR(10) NOT NULL UNIQUE,
    languagename VARCHAR(100) NOT NULL,
    nativename VARCHAR(100),

    flagurl VARCHAR(500),

    isactive BOOLEAN NOT NULL DEFAULT TRUE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 5. USER LANGUAGES
-- =========================================================

CREATE TABLE userlanguages (
    userlanguageid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    languageid INTEGER NOT NULL,

    currentlevel INTEGER NOT NULL DEFAULT 1,
    xp INTEGER NOT NULL DEFAULT 0,

    islearning BOOLEAN NOT NULL DEFAULT TRUE,

    startedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_userlanguages_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_userlanguages_languages
        FOREIGN KEY (languageid)
        REFERENCES languages(languageid),

    CONSTRAINT uq_userlanguages
        UNIQUE(userid, languageid)
);


-- =========================================================
-- 6. COURSES
-- =========================================================

CREATE TABLE courses (
    courseid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    languageid INTEGER NOT NULL,

    coursename VARCHAR(200) NOT NULL,
    description TEXT,

    imageurl VARCHAR(500),
    difficulty VARCHAR(50),

    totalxp INTEGER NOT NULL DEFAULT 0,

    ispublished BOOLEAN NOT NULL DEFAULT FALSE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_courses_languages
        FOREIGN KEY (languageid)
        REFERENCES languages(languageid)
);


-- =========================================================
-- 7. LESSONS
-- =========================================================

CREATE TABLE lessons (
    lessonid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    courseid INTEGER NOT NULL,

    lessonname VARCHAR(200) NOT NULL,
    description TEXT,

    lessonorder INTEGER NOT NULL DEFAULT 1,

    difficulty VARCHAR(50),

    xpreward INTEGER NOT NULL DEFAULT 20,

    estimatedminutes INTEGER NOT NULL DEFAULT 10,

    ispublished BOOLEAN NOT NULL DEFAULT TRUE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_lessons_courses
        FOREIGN KEY (courseid)
        REFERENCES courses(courseid)
        ON DELETE CASCADE
);


-- =========================================================
-- 8. USER LESSON PROGRESS
-- =========================================================

CREATE TABLE userlessonprogress (
    progressid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    lessonid INTEGER NOT NULL,

    progresspercent INTEGER NOT NULL DEFAULT 0,

    iscompleted BOOLEAN NOT NULL DEFAULT FALSE,

    score INTEGER NOT NULL DEFAULT 0,
    xpreceived INTEGER NOT NULL DEFAULT 0,

    startedat TIMESTAMPTZ,
    completedat TIMESTAMPTZ,

    lastaccessedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_userlessonprogress_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_userlessonprogress_lessons
        FOREIGN KEY (lessonid)
        REFERENCES lessons(lessonid)
        ON DELETE CASCADE,

    CONSTRAINT uq_userlessonprogress
        UNIQUE(userid, lessonid)
);


-- =========================================================
-- 9. VOCABULARY
-- =========================================================

CREATE TABLE vocabulary (
    vocabularyid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    languageid INTEGER NOT NULL,
    lessonid INTEGER,

    word VARCHAR(200) NOT NULL,
    pronunciation VARCHAR(200),

    meaning VARCHAR(500) NOT NULL,

    partofspeech VARCHAR(50),

    audiourl VARCHAR(500),
    imageurl VARCHAR(500),

    difficulty VARCHAR(50),

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_vocabulary_languages
        FOREIGN KEY (languageid)
        REFERENCES languages(languageid),

    CONSTRAINT fk_vocabulary_lessons
        FOREIGN KEY (lessonid)
        REFERENCES lessons(lessonid)
        ON DELETE SET NULL
);


-- =========================================================
-- 10. VOCABULARY EXAMPLES
-- =========================================================

CREATE TABLE vocabularyexamples (
    exampleid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vocabularyid INTEGER NOT NULL,

    examplesentence VARCHAR(1000) NOT NULL,
    translation VARCHAR(1000),

    audiourl VARCHAR(500),

    CONSTRAINT fk_vocabularyexamples_vocabulary
        FOREIGN KEY (vocabularyid)
        REFERENCES vocabulary(vocabularyid)
        ON DELETE CASCADE
);


-- =========================================================
-- 11. USER VOCABULARY
-- =========================================================

CREATE TABLE uservocabulary (
    uservocabularyid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    vocabularyid INTEGER NOT NULL,

    masterylevel INTEGER NOT NULL DEFAULT 0,

    isfavorite BOOLEAN NOT NULL DEFAULT FALSE,
    islearned BOOLEAN NOT NULL DEFAULT FALSE,

    reviewcount INTEGER NOT NULL DEFAULT 0,
    correctcount INTEGER NOT NULL DEFAULT 0,
    wrongcount INTEGER NOT NULL DEFAULT 0,

    lastreviewedat TIMESTAMPTZ,
    nextreviewat TIMESTAMPTZ,

    CONSTRAINT fk_uservocabulary_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_uservocabulary_vocabulary
        FOREIGN KEY (vocabularyid)
        REFERENCES vocabulary(vocabularyid)
        ON DELETE CASCADE,

    CONSTRAINT uq_uservocabulary
        UNIQUE(userid, vocabularyid)
);


-- =========================================================
-- 12. QUIZZES
-- =========================================================

CREATE TABLE quizzes (
    quizid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    lessonid INTEGER,

    quizname VARCHAR(200) NOT NULL,
    description TEXT,

    timelimitseconds INTEGER,

    passingscore INTEGER NOT NULL DEFAULT 60,
    xpreward INTEGER NOT NULL DEFAULT 30,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_quizzes_lessons
        FOREIGN KEY (lessonid)
        REFERENCES lessons(lessonid)
        ON DELETE SET NULL
);


-- =========================================================
-- 13. QUIZ QUESTIONS
-- =========================================================

CREATE TABLE quizquestions (
    questionid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    quizid INTEGER NOT NULL,

    questiontext VARCHAR(1000) NOT NULL,
    questiontype VARCHAR(50) NOT NULL,

    questionimageurl VARCHAR(500),
    questionaudiourl VARCHAR(500),

    points INTEGER NOT NULL DEFAULT 10,
    questionorder INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_quizquestions_quizzes
        FOREIGN KEY (quizid)
        REFERENCES quizzes(quizid)
        ON DELETE CASCADE
);


-- =========================================================
-- 14. QUIZ ANSWERS
-- =========================================================

CREATE TABLE quizanswers (
    answerid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    questionid INTEGER NOT NULL,

    answertext VARCHAR(500) NOT NULL,

    iscorrect BOOLEAN NOT NULL DEFAULT FALSE,

    answerorder INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_quizanswers_questions
        FOREIGN KEY (questionid)
        REFERENCES quizquestions(questionid)
        ON DELETE CASCADE
);


-- =========================================================
-- 15. QUIZ ATTEMPTS
-- =========================================================

CREATE TABLE quizattempts (
    attemptid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    quizid INTEGER NOT NULL,

    score INTEGER NOT NULL DEFAULT 0,
    totalquestions INTEGER NOT NULL DEFAULT 0,
    correctanswers INTEGER NOT NULL DEFAULT 0,
    xpreceived INTEGER NOT NULL DEFAULT 0,

    startedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completedat TIMESTAMPTZ,

    CONSTRAINT fk_quizattempts_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_quizattempts_quizzes
        FOREIGN KEY (quizid)
        REFERENCES quizzes(quizid)
        ON DELETE CASCADE
);


-- =========================================================
-- 16. GAMES
-- =========================================================

CREATE TABLE games (
    gameid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    languageid INTEGER NOT NULL,

    gamename VARCHAR(200) NOT NULL,
    description TEXT,

    gametype VARCHAR(50) NOT NULL,
    difficulty VARCHAR(50),

    imageurl VARCHAR(500),

    xpreward INTEGER NOT NULL DEFAULT 20,
    coinreward INTEGER NOT NULL DEFAULT 10,

    isactive BOOLEAN NOT NULL DEFAULT TRUE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_games_languages
        FOREIGN KEY (languageid)
        REFERENCES languages(languageid)
);


-- =========================================================
-- 17. GAME SESSIONS
-- =========================================================

CREATE TABLE gamesessions (
    gamesessionid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    gameid INTEGER NOT NULL,

    score INTEGER NOT NULL DEFAULT 0,

    correctanswers INTEGER NOT NULL DEFAULT 0,
    wronganswers INTEGER NOT NULL DEFAULT 0,

    xpreceived INTEGER NOT NULL DEFAULT 0,
    coinsreceived INTEGER NOT NULL DEFAULT 0,

    durationseconds INTEGER NOT NULL DEFAULT 0,

    startedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finishedat TIMESTAMPTZ,

    CONSTRAINT fk_gamesessions_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_gamesessions_games
        FOREIGN KEY (gameid)
        REFERENCES games(gameid)
        ON DELETE CASCADE
);


-- =========================================================
-- 18. ACHIEVEMENTS
-- =========================================================

CREATE TABLE achievements (
    achievementid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    achievementname VARCHAR(200) NOT NULL,
    description VARCHAR(500),

    iconurl VARCHAR(500),

    achievementtype VARCHAR(50),

    requirementvalue INTEGER NOT NULL DEFAULT 1,

    xpreward INTEGER NOT NULL DEFAULT 0,
    coinreward INTEGER NOT NULL DEFAULT 0,

    isactive BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 19. USER ACHIEVEMENTS
-- =========================================================

CREATE TABLE userachievements (
    userachievementid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    achievementid INTEGER NOT NULL,

    progressvalue INTEGER NOT NULL DEFAULT 0,

    iscompleted BOOLEAN NOT NULL DEFAULT FALSE,

    unlockedat TIMESTAMPTZ,

    CONSTRAINT fk_userachievements_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_userachievements_achievements
        FOREIGN KEY (achievementid)
        REFERENCES achievements(achievementid)
        ON DELETE CASCADE,

    CONSTRAINT uq_userachievement
        UNIQUE(userid, achievementid)
);


-- =========================================================
-- 20. DAILY STREAKS
-- =========================================================

CREATE TABLE dailystreaks (
    streakid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL UNIQUE,

    currentstreak INTEGER NOT NULL DEFAULT 0,
    longeststreak INTEGER NOT NULL DEFAULT 0,

    laststudydate DATE,

    totalstudydays INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_dailystreaks_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE
);


-- =========================================================
-- 21. LEADERBOARD
-- =========================================================

CREATE TABLE leaderboard (
    leaderboardid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    periodtype VARCHAR(30) NOT NULL,

    periodstart DATE NOT NULL,
    periodend DATE NOT NULL,

    xp INTEGER NOT NULL DEFAULT 0,

    rankposition INTEGER,

    updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_leaderboard_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE
);


-- =========================================================
-- 22. REWARDS
-- =========================================================

CREATE TABLE rewards (
    rewardid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    rewardname VARCHAR(200) NOT NULL,
    description VARCHAR(500),

    rewardtype VARCHAR(50) NOT NULL,

    rewardvalue INTEGER NOT NULL DEFAULT 0,
    costcoins INTEGER NOT NULL DEFAULT 0,

    imageurl VARCHAR(500),

    isactive BOOLEAN NOT NULL DEFAULT TRUE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 23. USER REWARDS
-- =========================================================

CREATE TABLE userrewards (
    userrewardid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,
    rewardid INTEGER NOT NULL,

    quantity INTEGER NOT NULL DEFAULT 1,

    redeemedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_userrewards_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_userrewards_rewards
        FOREIGN KEY (rewardid)
        REFERENCES rewards(rewardid)
);


-- =========================================================
-- 24. COMMENTS
-- =========================================================

CREATE TABLE comments (
    commentid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    lessonid INTEGER,
    courseid INTEGER,

    content VARCHAR(1000) NOT NULL,

    parentcommentid INTEGER,

    isdeleted BOOLEAN NOT NULL DEFAULT FALSE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_comments_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_comments_lessons
        FOREIGN KEY (lessonid)
        REFERENCES lessons(lessonid)
        ON DELETE NO ACTION,

    CONSTRAINT fk_comments_courses
        FOREIGN KEY (courseid)
        REFERENCES courses(courseid)
        ON DELETE NO ACTION,

    CONSTRAINT fk_comments_parent
        FOREIGN KEY (parentcommentid)
        REFERENCES comments(commentid)
        ON DELETE NO ACTION
);


-- =========================================================
-- 25. NOTIFICATIONS
-- =========================================================

CREATE TABLE notifications (
    notificationid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,

    notificationtype VARCHAR(50),

    isread BOOLEAN NOT NULL DEFAULT FALSE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notifications_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE
);


-- =========================================================
-- 26. INSERT USERS
-- =========================================================

INSERT INTO users (
    username,
    email,
    passwordhash,
    fullname,
    avatarurl,
    country,
    xp,
    level,
    coins,
    hearts,
    maxhearts,
    ispremium,
    isactive,
    role,
    lastloginat
)
VALUES
(
    'quan123',
    'quan@gmail.com',
    '$2b$12$DEMO_HASH_QUAN',
    'Lê Đình Quân',
    '/images/avatar/quan.png',
    'Vietnam',
    1250,
    5,
    350,
    5,
    5,
    FALSE,
    TRUE,
    'User',
    NOW()
),
(
    'admin',
    'admin@languagegame.com',
    '$2b$12$DEMO_HASH_ADMIN',
    'Administrator',
    '/images/avatar/admin.png',
    'Vietnam',
    5000,
    20,
    5000,
    5,
    5,
    TRUE,
    TRUE,
    'Admin',
    NOW()
),
(
    'nguyenan',
    'an@gmail.com',
    '$2b$12$DEMO_HASH_AN',
    'Nguyễn An',
    '/images/avatar/an.png',
    'Vietnam',
    850,
    4,
    180,
    5,
    5,
    FALSE,
    TRUE,
    'User',
    NOW()
);


-- =========================================================
-- 27. LANGUAGES
-- =========================================================

INSERT INTO languages (
    languagecode,
    languagename,
    nativename,
    flagurl
)
VALUES
('en', 'English', 'English', '/images/flags/en.png'),
('ja', 'Japanese', '日本語', '/images/flags/jp.png'),
('ko', 'Korean', '한국어', '/images/flags/kr.png'),
('zh', 'Chinese', '中文', '/images/flags/cn.png'),
('fr', 'French', 'Français', '/images/flags/fr.png');


-- =========================================================
-- 28. USER LANGUAGES
-- =========================================================

INSERT INTO userlanguages (
    userid,
    languageid,
    currentlevel,
    xp,
    islearning
)
VALUES
(1, 1, 5, 1250, TRUE),
(1, 2, 2, 320, TRUE),
(3, 1, 4, 850, TRUE);


-- =========================================================
-- 29. COURSES
-- =========================================================

INSERT INTO courses (
    languageid,
    coursename,
    description,
    imageurl,
    difficulty,
    totalxp,
    ispublished
)
VALUES
(
    1,
    'English Beginner',
    'Khóa học tiếng Anh cơ bản dành cho người mới bắt đầu.',
    '/images/courses/english-basic.jpg',
    'Beginner',
    500,
    TRUE
),
(
    1,
    'English Communication',
    'Học tiếng Anh giao tiếp trong các tình huống thực tế.',
    '/images/courses/english-speaking.jpg',
    'Intermediate',
    1000,
    TRUE
),
(
    2,
    'Japanese Beginner',
    'Tiếng Nhật cơ bản cho người mới bắt đầu.',
    '/images/courses/japanese-basic.jpg',
    'Beginner',
    600,
    TRUE
),
(
    3,
    'Korean Beginner',
    'Tiếng Hàn cơ bản.',
    '/images/courses/korean-basic.jpg',
    'Beginner',
    600,
    TRUE
);


-- =========================================================
-- 30. LESSONS
-- =========================================================

INSERT INTO lessons (
    courseid,
    lessonname,
    description,
    lessonorder,
    difficulty,
    xpreward,
    estimatedminutes
)
VALUES
(1, 'Greetings - Chào hỏi',
 'Học cách chào hỏi và giới thiệu bản thân bằng tiếng Anh.',
 1, 'Beginner', 20, 10),

(1, 'Numbers - Số đếm',
 'Học số đếm từ 1 đến 100.',
 2, 'Beginner', 20, 10),

(1, 'Family - Gia đình',
 'Từ vựng về các thành viên trong gia đình.',
 3, 'Beginner', 25, 15),

(1, 'Daily Activities',
 'Từ vựng và câu giao tiếp về hoạt động hàng ngày.',
 4, 'Beginner', 30, 15),

(2, 'English Conversation',
 'Hội thoại tiếng Anh cơ bản.',
 1, 'Intermediate', 40, 20),

(3, 'Hiragana',
 'Làm quen với bảng chữ cái Hiragana.',
 1, 'Beginner', 30, 20),

(3, 'Japanese Greetings',
 'Các câu chào hỏi trong tiếng Nhật.',
 2, 'Beginner', 30, 15);


-- =========================================================
-- 31. VOCABULARY
-- =========================================================

INSERT INTO vocabulary (
    languageid,
    lessonid,
    word,
    pronunciation,
    meaning,
    partofspeech,
    audiourl,
    imageurl,
    difficulty
)
VALUES
(1, 1, 'Hello', '/həˈloʊ/', 'Xin chào',
 'Interjection', '/audio/hello.mp3',
 '/images/vocabulary/hello.jpg', 'Beginner'),

(1, 1, 'Good morning', '/ɡʊd ˈmɔːrnɪŋ/', 'Chào buổi sáng',
 'Phrase', '/audio/good-morning.mp3',
 '/images/vocabulary/morning.jpg', 'Beginner'),

(1, 1, 'Goodbye', '/ˌɡʊdˈbaɪ/', 'Tạm biệt',
 'Interjection', '/audio/goodbye.mp3',
 '/images/vocabulary/goodbye.jpg', 'Beginner'),

(1, 3, 'Father', '/ˈfɑːðər/', 'Bố, cha',
 'Noun', '/audio/father.mp3',
 '/images/vocabulary/father.jpg', 'Beginner'),

(1, 3, 'Mother', '/ˈmʌðər/', 'Mẹ',
 'Noun', '/audio/mother.mp3',
 '/images/vocabulary/mother.jpg', 'Beginner'),

(1, 3, 'Brother', '/ˈbrʌðər/', 'Anh/em trai',
 'Noun', '/audio/brother.mp3',
 '/images/vocabulary/brother.jpg', 'Beginner'),

(1, 3, 'Sister', '/ˈsɪstər/', 'Chị/em gái',
 'Noun', '/audio/sister.mp3',
 '/images/vocabulary/sister.jpg', 'Beginner'),

(1, 4, 'Eat', '/iːt/', 'Ăn',
 'Verb', '/audio/eat.mp3',
 '/images/vocabulary/eat.jpg', 'Beginner'),

(1, 4, 'Sleep', '/sliːp/', 'Ngủ',
 'Verb', '/audio/sleep.mp3',
 '/images/vocabulary/sleep.jpg', 'Beginner'),

(1, 4, 'Work', '/wɜːrk/', 'Làm việc',
 'Verb', '/audio/work.mp3',
 '/images/vocabulary/work.jpg', 'Beginner'),

(2, 6, 'こんにちは', 'Konnichiwa', 'Xin chào',
 'Phrase', '/audio/konnichiwa.mp3',
 '/images/vocabulary/konnichiwa.jpg', 'Beginner'),

(2, 7, 'ありがとう', 'Arigatou', 'Cảm ơn',
 'Phrase', '/audio/arigatou.mp3',
 '/images/vocabulary/arigatou.jpg', 'Beginner');


-- =========================================================
-- 32. VOCABULARY EXAMPLES
-- =========================================================

INSERT INTO vocabularyexamples (
    vocabularyid,
    examplesentence,
    translation
)
VALUES
(1, 'Hello! How are you?', 'Xin chào! Bạn khỏe không?'),
(2, 'Good morning, everyone!', 'Chào buổi sáng mọi người!'),
(3, 'Goodbye! See you tomorrow.', 'Tạm biệt! Hẹn gặp bạn ngày mai.'),
(4, 'My father is a teacher.', 'Bố tôi là giáo viên.'),
(5, 'My mother is a doctor.', 'Mẹ tôi là bác sĩ.'),
(8, 'I eat breakfast at 7 AM.', 'Tôi ăn sáng lúc 7 giờ.');


-- =========================================================
-- 33. USER VOCABULARY
-- =========================================================

INSERT INTO uservocabulary (
    userid,
    vocabularyid,
    masterylevel,
    isfavorite,
    islearned,
    reviewcount,
    correctcount,
    wrongcount,
    lastreviewedat,
    nextreviewat
)
VALUES
(
    1, 1, 5, TRUE, TRUE,
    10, 9, 1,
    NOW(),
    NOW() + INTERVAL '3 days'
),
(
    1, 2, 3, TRUE, TRUE,
    6, 5, 1,
    NOW(),
    NOW() + INTERVAL '2 days'
),
(
    1, 4, 2, FALSE, FALSE,
    3, 2, 1,
    NOW(),
    NOW() + INTERVAL '1 day'
);


-- =========================================================
-- 34. QUIZZES
-- =========================================================

INSERT INTO quizzes (
    lessonid,
    quizname,
    description,
    timelimitseconds,
    passingscore,
    xpreward
)
VALUES
(1, 'Greetings Quiz', 'Kiểm tra từ vựng chào hỏi.', 120, 60, 30),
(3, 'Family Vocabulary Quiz', 'Kiểm tra từ vựng về gia đình.', 180, 60, 40),
(4, 'Daily Activities Quiz', 'Kiểm tra từ vựng hoạt động hàng ngày.', 180, 60, 40);


-- =========================================================
-- 35. QUIZ QUESTIONS
-- =========================================================

INSERT INTO quizquestions (
    quizid,
    questiontext,
    questiontype,
    points,
    questionorder
)
VALUES
(1, '"Hello" có nghĩa là gì?', 'MultipleChoice', 10, 1),
(1, '"Good morning" có nghĩa là gì?', 'MultipleChoice', 10, 2),
(1, '"Goodbye" có nghĩa là gì?', 'MultipleChoice', 10, 3),
(2, '"Father" có nghĩa là gì?', 'MultipleChoice', 10, 1),
(2, '"Mother" có nghĩa là gì?', 'MultipleChoice', 10, 2),
(2, '"Brother" có nghĩa là gì?', 'MultipleChoice', 10, 3);


-- =========================================================
-- 36. QUIZ ANSWERS
-- =========================================================

INSERT INTO quizanswers (
    questionid,
    answertext,
    iscorrect,
    answerorder
)
VALUES
(1, 'Xin chào', TRUE, 1),
(1, 'Tạm biệt', FALSE, 2),
(1, 'Cảm ơn', FALSE, 3),
(1, 'Xin lỗi', FALSE, 4),

(2, 'Chào buổi tối', FALSE, 1),
(2, 'Chào buổi sáng', TRUE, 2),
(2, 'Chào buổi trưa', FALSE, 3),
(2, 'Tạm biệt', FALSE, 4),

(3, 'Xin chào', FALSE, 1),
(3, 'Cảm ơn', FALSE, 2),
(3, 'Tạm biệt', TRUE, 3),
(3, 'Xin lỗi', FALSE, 4),

(4, 'Mẹ', FALSE, 1),
(4, 'Bố', TRUE, 2),
(4, 'Anh trai', FALSE, 3),
(4, 'Em gái', FALSE, 4),

(5, 'Mẹ', TRUE, 1),
(5, 'Bố', FALSE, 2),
(5, 'Chị gái', FALSE, 3),
(5, 'Em trai', FALSE, 4),

(6, 'Anh/em trai', TRUE, 1),
(6, 'Anh/em gái', FALSE, 2),
(6, 'Bố', FALSE, 3),
(6, 'Mẹ', FALSE, 4);


-- =========================================================
-- 37. QUIZ ATTEMPTS
-- =========================================================

INSERT INTO quizattempts (
    userid,
    quizid,
    score,
    totalquestions,
    correctanswers,
    xpreceived,
    startedat,
    completedat
)
VALUES
(
    1, 1, 100, 3, 3, 30,
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '25 minutes'
),
(
    3, 1, 66, 3, 2, 20,
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '23 hours 50 minutes'
);


-- =========================================================
-- 38. GAMES
-- =========================================================

INSERT INTO games (
    languageid,
    gamename,
    description,
    gametype,
    difficulty,
    imageurl,
    xpreward,
    coinreward
)
VALUES
(
    1,
    'Word Match',
    'Nối từ tiếng Anh với nghĩa tiếng Việt.',
    'Matching',
    'Easy',
    '/images/games/word-match.jpg',
    20,
    10
),
(
    1,
    'Word Scramble',
    'Sắp xếp các chữ cái thành từ đúng.',
    'Scramble',
    'Medium',
    '/images/games/word-scramble.jpg',
    30,
    15
),
(
    1,
    'Listen & Choose',
    'Nghe phát âm và chọn đáp án đúng.',
    'Listening',
    'Medium',
    '/images/games/listening.jpg',
    30,
    15
),
(
    1,
    'Vocabulary Rush',
    'Trả lời nhanh các câu hỏi từ vựng.',
    'QuizRush',
    'Hard',
    '/images/games/vocabulary-rush.jpg',
    50,
    30
),
(
    2,
    'Japanese Hiragana Match',
    'Nối chữ Hiragana với cách đọc.',
    'Matching',
    'Easy',
    '/images/games/hiragana.jpg',
    25,
    15
);


-- =========================================================
-- 39. GAME SESSIONS
-- =========================================================

INSERT INTO gamesessions (
    userid,
    gameid,
    score,
    correctanswers,
    wronganswers,
    xpreceived,
    coinsreceived,
    durationseconds,
    startedat,
    finishedat
)
VALUES
(
    1, 1, 950, 19, 1, 20, 10, 180,
    NOW() - INTERVAL '60 minutes',
    NOW() - INTERVAL '57 minutes'
),
(
    1, 2, 1200, 15, 5, 30, 15, 240,
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '41 minutes'
),
(
    3, 1, 700, 14, 6, 15, 8, 200,
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '23 hours 56 minutes'
);


-- =========================================================
-- 40. ACHIEVEMENTS
-- =========================================================

INSERT INTO achievements (
    achievementname,
    description,
    iconurl,
    achievementtype,
    requirementvalue,
    xpreward,
    coinreward
)
VALUES
(
    'First Lesson',
    'Hoàn thành bài học đầu tiên.',
    '/images/achievements/first-lesson.png',
    'LessonCompleted',
    1,
    50,
    20
),
(
    'Vocabulary Master',
    'Học 100 từ vựng.',
    '/images/achievements/vocabulary.png',
    'VocabularyLearned',
    100,
    200,
    100
),
(
    '7 Day Streak',
    'Học liên tục 7 ngày.',
    '/images/achievements/streak7.png',
    'Streak',
    7,
    100,
    50
),
(
    'Game Master',
    'Chơi 50 game.',
    '/images/achievements/game-master.png',
    'GamePlayed',
    50,
    200,
    100
),
(
    'Quiz Champion',
    'Đạt 100% trong một bài quiz.',
    '/images/achievements/quiz.png',
    'QuizPerfect',
    1,
    100,
    50
);


-- =========================================================
-- 41. USER ACHIEVEMENTS
-- =========================================================

INSERT INTO userachievements (
    userid,
    achievementid,
    progressvalue,
    iscompleted,
    unlockedat
)
VALUES
(1, 1, 1, TRUE, NOW() - INTERVAL '10 days'),
(1, 2, 42, FALSE, NULL),
(1, 3, 5, FALSE, NULL),
(1, 4, 18, FALSE, NULL),
(1, 5, 1, TRUE, NOW() - INTERVAL '2 days');


-- =========================================================
-- 42. DAILY STREAKS
-- =========================================================

INSERT INTO dailystreaks (
    userid,
    currentstreak,
    longeststreak,
    laststudydate,
    totalstudydays
)
VALUES
(1, 5, 12, CURRENT_DATE, 35),
(2, 20, 30, CURRENT_DATE, 100),
(3, 2, 7, CURRENT_DATE, 15);


-- =========================================================
-- 43. LEADERBOARD
-- =========================================================

INSERT INTO leaderboard (
    userid,
    periodtype,
    periodstart,
    periodend,
    xp,
    rankposition
)
VALUES
(
    1,
    'Weekly',
    CURRENT_DATE - 6,
    CURRENT_DATE,
    450,
    1
),
(
    3,
    'Weekly',
    CURRENT_DATE - 6,
    CURRENT_DATE,
    320,
    2
),
(
    2,
    'Weekly',
    CURRENT_DATE - 6,
    CURRENT_DATE,
    300,
    3
);


-- =========================================================
-- 44. REWARDS
-- =========================================================

INSERT INTO rewards (
    rewardname,
    description,
    rewardtype,
    rewardvalue,
    costcoins,
    imageurl
)
VALUES
(
    'Extra Heart',
    'Thêm 1 tim.',
    'Heart',
    1,
    50,
    '/images/rewards/heart.png'
),
(
    '100 XP',
    'Nhận thêm 100 XP.',
    'XP',
    100,
    100,
    '/images/rewards/xp.png'
),
(
    '500 XP',
    'Nhận thêm 500 XP.',
    'XP',
    500,
    400,
    '/images/rewards/xp500.png'
),
(
    'Streak Freeze',
    'Bảo vệ chuỗi học trong một ngày.',
    'StreakFreeze',
    1,
    200,
    '/images/rewards/freeze.png'
),
(
    'Extra Coin',
    'Nhận thêm 100 coin.',
    'Coin',
    100,
    100,
    '/images/rewards/coin.png'
);


-- =========================================================
-- 45. USER REWARDS
-- =========================================================

INSERT INTO userrewards (
    userid,
    rewardid,
    quantity
)
VALUES
(1, 1, 2),
(1, 4, 1),
(3, 1, 1);


-- =========================================================
-- 46. USER LESSON PROGRESS
-- =========================================================

INSERT INTO userlessonprogress (
    userid,
    lessonid,
    progresspercent,
    iscompleted,
    score,
    xpreceived,
    startedat,
    completedat,
    lastaccessedat
)
VALUES
(
    1,
    1,
    100,
    TRUE,
    100,
    20,
    NOW() - INTERVAL '10 days',
    NOW() - INTERVAL '9 days 23 hours 45 minutes',
    NOW() - INTERVAL '10 days'
),
(
    1,
    2,
    100,
    TRUE,
    90,
    20,
    NOW() - INTERVAL '8 days',
    NOW() - INTERVAL '7 days 23 hours 50 minutes',
    NOW() - INTERVAL '8 days'
),
(
    1,
    3,
    70,
    FALSE,
    70,
    0,
    NOW() - INTERVAL '2 days',
    NULL,
    NOW()
),
(
    3,
    1,
    100,
    TRUE,
    80,
    20,
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '2 days 23 hours 50 minutes',
    NOW() - INTERVAL '3 days'
);


-- =========================================================
-- 47. COMMENTS
-- =========================================================

INSERT INTO comments (
    userid,
    lessonid,
    courseid,
    content
)
VALUES
(
    1,
    1,
    1,
    'Bài này khá dễ hiểu, phần phát âm rất hữu ích.'
),
(
    3,
    1,
    1,
    'Mình thích phần quiz sau bài học.'
),
(
    1,
    3,
    1,
    'Có thể thêm nhiều từ vựng hơn không?'
);


-- =========================================================
-- 48. NOTIFICATIONS
-- =========================================================

INSERT INTO notifications (
    userid,
    title,
    message,
    notificationtype
)
VALUES
(
    1,
    'Chúc mừng!',
    'Bạn đã hoàn thành bài học Greetings.',
    'Lesson'
),
(
    1,
    'Chuỗi học 5 ngày!',
    'Bạn đang có chuỗi học liên tục 5 ngày.',
    'Streak'
),
(
    1,
    'Thành tích mới!',
    'Bạn đã mở khóa thành tích Quiz Champion.',
    'Achievement'
),
(
    3,
    'Quay lại học nào!',
    'Hôm nay bạn chưa hoàn thành bài học.',
    'Reminder'
);


-- =========================================================
-- 49. SUBSCRIPTIONS
-- =========================================================

INSERT INTO subscriptions (
    userid,
    planname,
    price,
    startdate,
    enddate,
    status,
    paymentmethod,
    transactioncode
)
VALUES
(
    2,
    'Premium Monthly',
    99000,
    NOW() - INTERVAL '10 days',
    NOW() + INTERVAL '20 days',
    'Active',
    'Momo',
    'DEMO-MOMO-0001'
);


-- =========================================================
-- 50. INDEXES
-- =========================================================

CREATE INDEX ix_users_email
ON users(email);

CREATE INDEX ix_userlanguages_userid
ON userlanguages(userid);

CREATE INDEX ix_courses_languageid
ON courses(languageid);

CREATE INDEX ix_lessons_courseid
ON lessons(courseid);

CREATE INDEX ix_vocabulary_languageid
ON vocabulary(languageid);

CREATE INDEX ix_vocabulary_lessonid
ON vocabulary(lessonid);

CREATE INDEX ix_uservocabulary_userid
ON uservocabulary(userid);

CREATE INDEX ix_quizquestions_quizid
ON quizquestions(quizid);

CREATE INDEX ix_gamesessions_userid
ON gamesessions(userid);

CREATE INDEX ix_gamesessions_gameid
ON gamesessions(gameid);

CREATE INDEX ix_leaderboard_period
ON leaderboard(periodtype, periodstart, periodend);

CREATE INDEX ix_notifications_userid
ON notifications(userid, isread);


-- =========================================================
-- 51. TEST
-- =========================================================

SELECT * FROM users;

SELECT * FROM languages;

SELECT
    c.courseid,
    c.coursename,
    l.languagename,
    c.difficulty,
    c.totalxp
FROM courses c
INNER JOIN languages l
    ON c.languageid = l.languageid;

SELECT
    le.lessonid,
    le.lessonname,
    c.coursename,
    le.lessonorder,
    le.xpreward
FROM lessons le
INNER JOIN courses c
    ON le.courseid = c.courseid
ORDER BY c.courseid, le.lessonorder;

SELECT
    v.vocabularyid,
    l.languagename,
    v.word,
    v.pronunciation,
    v.meaning
FROM vocabulary v
INNER JOIN languages l
    ON v.languageid = l.languageid;

SELECT
    u.username,
    le.lessonname,
    p.progresspercent,
    p.iscompleted,
    p.score,
    p.xpreceived
FROM userlessonprogress p
INNER JOIN users u
    ON p.userid = u.userid
INNER JOIN lessons le
    ON p.lessonid = le.lessonid
ORDER BY u.userid, le.lessonorder;

SELECT
    lb.rankposition,
    u.username,
    u.fullname,
    lb.xp,
    lb.periodtype
FROM leaderboard lb
INNER JOIN users u
    ON lb.userid = u.userid
WHERE lb.periodtype = 'Weekly'
ORDER BY lb.rankposition;

SELECT
    u.username,
    a.achievementname,
    ua.progressvalue,
    a.requirementvalue,
    ua.iscompleted,
    ua.unlockedat
FROM userachievements ua
INNER JOIN users u
    ON ua.userid = u.userid
INNER JOIN achievements a
    ON ua.achievementid = a.achievementid
WHERE u.userid = 1;

SELECT
    u.username,
    g.gamename,
    gs.score,
    gs.correctanswers,
    gs.wronganswers,
    gs.xpreceived,
    gs.coinsreceived,
    gs.durationseconds
FROM gamesessions gs
INNER JOIN users u
    ON gs.userid = u.userid
INNER JOIN games g
    ON gs.gameid = g.gameid
ORDER BY gs.startedat DESC;

SELECT
    q.quizname,
    qq.questionid,
    qq.questiontext,
    qa.answertext,
    qa.iscorrect
FROM quizzes q
INNER JOIN quizquestions qq
    ON q.quizid = qq.quizid
INNER JOIN quizanswers qa
    ON qq.questionid = qa.questionid
ORDER BY q.quizid, qq.questionid, qa.answerorder;