-- =========================================================
-- LINGUA QUEST
-- RANKED / PVP - POSTGRESQL
-- =========================================================

-- =========================================================
-- 1. RANK SEASONS
-- =========================================================

CREATE TABLE IF NOT EXISTS rankseasons
(
    seasonid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seasonname VARCHAR(100) NOT NULL,

    startdate TIMESTAMPTZ NOT NULL,

    enddate TIMESTAMPTZ NOT NULL,

    isactive BOOLEAN NOT NULL DEFAULT FALSE,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 2. RANK TIERS
-- =========================================================

CREATE TABLE IF NOT EXISTS ranktiers
(
    ranktierid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    rankname VARCHAR(50) NOT NULL,

    rankorder INTEGER NOT NULL,

    minrating INTEGER NOT NULL,

    maxrating INTEGER,

    iconurl VARCHAR(500),

    description VARCHAR(500)
);


-- =========================================================
-- 3. PLAYER RANK
-- =========================================================

CREATE TABLE IF NOT EXISTS playerranks
(
    playerrankid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    seasonid INTEGER NOT NULL,

    ranktierid INTEGER NOT NULL,

    rating INTEGER NOT NULL DEFAULT 1000,

    -- Giữ rankpoint vì schema gốc có.
    -- Nếu rankRepository không sử dụng rankpoint thì có thể bỏ.
    rankpoint INTEGER NOT NULL DEFAULT 0,

    wins INTEGER NOT NULL DEFAULT 0,

    losses INTEGER NOT NULL DEFAULT 0,

    draws INTEGER NOT NULL DEFAULT 0,

    totalmatches INTEGER NOT NULL DEFAULT 0,

    winstreak INTEGER NOT NULL DEFAULT 0,

    bestwinstreak INTEGER NOT NULL DEFAULT 0,

    highestrating INTEGER NOT NULL DEFAULT 1000,

    placementmatches INTEGER NOT NULL DEFAULT 0,

    isplacementcompleted BOOLEAN NOT NULL DEFAULT FALSE,

    lastmatchat TIMESTAMPTZ,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_playerranks_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_playerranks_seasons
        FOREIGN KEY (seasonid)
        REFERENCES rankseasons(seasonid),

    CONSTRAINT fk_playerranks_ranktiers
        FOREIGN KEY (ranktierid)
        REFERENCES ranktiers(ranktierid),

    CONSTRAINT uq_playerrank_season
        UNIQUE(userid, seasonid)
);


-- =========================================================
-- 4. MATCHMAKING QUEUE
-- =========================================================

CREATE TABLE IF NOT EXISTS matchmakingqueue
(
    queueid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    seasonid INTEGER NOT NULL,

    rating INTEGER NOT NULL,

    ranktierid INTEGER NOT NULL,

    languageid INTEGER NOT NULL,

    queuestatus VARCHAR(30) NOT NULL DEFAULT 'Waiting',

    searchrange INTEGER NOT NULL DEFAULT 100,

    joinedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    matchedat TIMESTAMPTZ,

    cancelledat TIMESTAMPTZ,

    CONSTRAINT fk_matchmakingqueue_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchmakingqueue_seasons
        FOREIGN KEY (seasonid)
        REFERENCES rankseasons(seasonid),

    CONSTRAINT fk_matchmakingqueue_ranktiers
        FOREIGN KEY (ranktierid)
        REFERENCES ranktiers(ranktierid),

    CONSTRAINT fk_matchmakingqueue_languages
        FOREIGN KEY (languageid)
        REFERENCES languages(languageid)
);


-- =========================================================
-- 5. MATCHES
-- =========================================================

CREATE TABLE IF NOT EXISTS matches
(
    matchid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seasonid INTEGER NOT NULL,

    languageid INTEGER NOT NULL,

    matchtype VARCHAR(30) NOT NULL DEFAULT 'Ranked',

    matchstatus VARCHAR(30) NOT NULL DEFAULT 'Waiting',

    totalquestions INTEGER NOT NULL DEFAULT 10,

    currentquestion INTEGER NOT NULL DEFAULT 0,

    player1score INTEGER NOT NULL DEFAULT 0,

    player2score INTEGER NOT NULL DEFAULT 0,

    winneruserid INTEGER,

    loseruserid INTEGER,

    startedat TIMESTAMPTZ,

    finishedat TIMESTAMPTZ,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_matches_seasons
        FOREIGN KEY (seasonid)
        REFERENCES rankseasons(seasonid),

    CONSTRAINT fk_matches_languages
        FOREIGN KEY (languageid)
        REFERENCES languages(languageid),

    CONSTRAINT fk_matches_winner
        FOREIGN KEY (winneruserid)
        REFERENCES users(userid),

    CONSTRAINT fk_matches_loser
        FOREIGN KEY (loseruserid)
        REFERENCES users(userid)
);


-- =========================================================
-- 6. MATCH PLAYERS
-- =========================================================

CREATE TABLE IF NOT EXISTS matchplayers
(
    matchplayerid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    matchid BIGINT NOT NULL,

    userid INTEGER NOT NULL,

    playernumber INTEGER NOT NULL,

    ratingbefore INTEGER NOT NULL,

    ratingafter INTEGER,

    score INTEGER NOT NULL DEFAULT 0,

    correctanswers INTEGER NOT NULL DEFAULT 0,

    wronganswers INTEGER NOT NULL DEFAULT 0,

    xpreceived INTEGER NOT NULL DEFAULT 0,

    coinsreceived INTEGER NOT NULL DEFAULT 0,

    ratingchange INTEGER NOT NULL DEFAULT 0,

    iswinner BOOLEAN NOT NULL DEFAULT FALSE,

    isloser BOOLEAN NOT NULL DEFAULT FALSE,

    isdisconnected BOOLEAN NOT NULL DEFAULT FALSE,

    joinedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    finishedat TIMESTAMPTZ,

    CONSTRAINT fk_matchplayers_matches
        FOREIGN KEY (matchid)
        REFERENCES matches(matchid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchplayers_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT uq_matchplayer
        UNIQUE(matchid, userid),

    CONSTRAINT uq_matchplayernumber
        UNIQUE(matchid, playernumber)
);


-- =========================================================
-- 7. MATCH QUESTIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS matchquestions
(
    matchquestionid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    matchid BIGINT NOT NULL,

    questionid INTEGER,

    questionnumber INTEGER NOT NULL,

    questiontext VARCHAR(1000) NOT NULL,

    correctanswer VARCHAR(500) NOT NULL,

    timelimitseconds INTEGER NOT NULL DEFAULT 10,

    CONSTRAINT fk_matchquestions_matches
        FOREIGN KEY (matchid)
        REFERENCES matches(matchid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchquestions_quizquestions
        FOREIGN KEY (questionid)
        REFERENCES quizquestions(questionid)
        ON DELETE SET NULL,

    CONSTRAINT uq_matchquestionnumber
        UNIQUE(matchid, questionnumber)
);


-- =========================================================
-- 8. MATCH ANSWERS
-- =========================================================

CREATE TABLE IF NOT EXISTS matchanswers
(
    matchanswerid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    matchid BIGINT NOT NULL,

    matchquestionid BIGINT NOT NULL,

    userid INTEGER NOT NULL,

    answertext VARCHAR(500),

    iscorrect BOOLEAN NOT NULL DEFAULT FALSE,

    score INTEGER NOT NULL DEFAULT 0,

    answertimemilliseconds INTEGER,

    answeredat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_matchanswers_matches
        FOREIGN KEY (matchid)
        REFERENCES matches(matchid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchanswers_questions
        FOREIGN KEY (matchquestionid)
        REFERENCES matchquestions(matchquestionid)
        ON DELETE CASCADE,

    CONSTRAINT fk_matchanswers_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT uq_matchanswer
        UNIQUE(matchquestionid, userid)
);


-- =========================================================
-- 9. RANK HISTORY
-- =========================================================

CREATE TABLE IF NOT EXISTS rankhistory
(
    rankhistoryid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    userid INTEGER NOT NULL,

    seasonid INTEGER NOT NULL,

    matchid BIGINT,

    oldrating INTEGER NOT NULL,

    newrating INTEGER NOT NULL,

    ratingchange INTEGER NOT NULL,

    oldranktierid INTEGER NOT NULL,

    newranktierid INTEGER NOT NULL,

    result VARCHAR(30) NOT NULL,

    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_rankhistory_users
        FOREIGN KEY (userid)
        REFERENCES users(userid)
        ON DELETE CASCADE,

    CONSTRAINT fk_rankhistory_seasons
        FOREIGN KEY (seasonid)
        REFERENCES rankseasons(seasonid),

    CONSTRAINT fk_rankhistory_matches
        FOREIGN KEY (matchid)
        REFERENCES matches(matchid),

    CONSTRAINT fk_rankhistory_oldtier
        FOREIGN KEY (oldranktierid)
        REFERENCES ranktiers(ranktierid),

    CONSTRAINT fk_rankhistory_newtier
        FOREIGN KEY (newranktierid)
        REFERENCES ranktiers(ranktierid)
);


-- =========================================================
-- 10. INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS ix_matchmakingqueue_status
ON matchmakingqueue(queuestatus, languageid, rating);


CREATE INDEX IF NOT EXISTS ix_playerranks_rating
ON playerranks(seasonid, rating);


CREATE INDEX IF NOT EXISTS ix_matches_status
ON matches(matchstatus);


CREATE INDEX IF NOT EXISTS ix_matchplayers_user
ON matchplayers(userid);


CREATE INDEX IF NOT EXISTS ix_rankhistory_user
ON rankhistory(userid, createdat);


-- =========================================================
-- 11. INDEX HỖ TRỢ MATCHMAKING
-- =========================================================

CREATE INDEX IF NOT EXISTS ix_matchmakingqueue_search
ON matchmakingqueue(
    seasonid,
    languageid,
    queuestatus,
    rating
);


-- =========================================================
-- 12. INDEX HỖ TRỢ MATCH QUESTIONS
-- =========================================================

CREATE INDEX IF NOT EXISTS ix_matchquestions_match
ON matchquestions(matchid, questionnumber);


-- =========================================================
-- 13. INDEX HỖ TRỢ MATCH ANSWERS
-- =========================================================

CREATE INDEX IF NOT EXISTS ix_matchanswers_user
ON matchanswers(userid);


-- =========================================================
-- 14. KIỂM TRA
-- =========================================================

SELECT *
FROM rankseasons;

SELECT *
FROM ranktiers;

SELECT *
FROM playerranks;

SELECT *
FROM matchmakingqueue;

SELECT *
FROM matches;

SELECT *
FROM matchplayers;

SELECT *
FROM matchquestions;

SELECT *
FROM matchanswers;

SELECT *
FROM rankhistory;